export const REQUEST_POPULAR_DATA = "REQUEST_POPULAR_DATA";
export const RECEIVE_POPULAR_DATA = "RECEIVE_POPULAR_DATA";
export const REQUEST_FILTER_DATA = "REQUEST_FILTER_DATA";
export const RECEIVE_FILTER_DATA = "RECEIVE_FILTER_DATA";
export const REQUEST_SEARCH_DATA = "REQUEST_SEARCH_DATA";
export const RECEIVE_SEARCH_DATA = "RECEIVE_SEARCH_DATA";
